### ISSUE TITLE
Erreur MySQL quand on refresh le widget:

### ISSUE THREAD

**Issue by Barichon21** [Caelion/jeedom_eesmart_d2l#1]
`[2020-02-06 22:12:51][ERROR] : Erreur exécution de la commande [Appartement][Compteur Linky][Rafraichir] : [MySQL] Error code : 22007 (1366). Incorrect integer value: '' for column `jeedom`.`cmd`.`isVisible` at row 1  : UPDATE `cmd` SET `id` = :id, `logicalId` = :logicalId, `generic_type` = :generic_type, `eqType` = :eqType, `name` = :name, `order` = :order, `type` = :type, `subType` = :subType, `eqLogic_id` = :eqLogic_id, `isHistorized` = :isHistorized, `unite` = :unite, `configuration` = :configuration, `template` = :template, `display` = :display, `value` = :value, `isVisible` = :isVisible, `alert` = :alert WHERE id = :id
`

**Comment by Caelion** [comment]
Correction vue ensemble et poussé sur le github
